### ISSUE TITLE
`fmt` can create invalid-utf8 string

### ISSUE THREAD

**Issue by shinmao** [Kogia-sima/itoap#3]
### The source of unsoundness
https://github.com/Kogia-sima/itoap/blob/1cdecb16fb9986f1d221ba51ec99ce8f62b2f0be/src/lib.rs#L221-L225
Hi, we consider the function `fmt` is unsound because it can pass any `u8`, `u16`, `u32`, `u64`, `u128`, `usize` to `str::from_utf8_unchecked` and assume it is utf8-encoding. It could leads to undefined behavior.

**Comment by Kogia-sima** [comment]
Any decimal character (1, 5, -, etc.) is a valid UTF-8 character, so this operation is actually safe.

**Comment by shinmao** [comment]
@Kogia-sima I think utf8 only covers values from 0-127, which is the range only for u8.
